# Configuration for filtering ServiceNow tickets into a Q&A dataset

[state]
allowed_states = ["Closed", "Resolved"]

[close_codes]
allowed = [
    "Solved (Permanently)",
    "Solved (Work Around)",
    "Resolved by Requester",
]
rejected = []

[contact_types]
allowed = [
    "User Web Interface",
    "Email",
]
rejected = []

[auto_generated]
reject_if_short_description_matches = [
    "cori",
    "\\b(?:quota\\b.*\\bincrease|increase\\b.*\\bquota)\\b",
    "newt",
    "\\b(?:ip|reservation|access|database|cname)\\s+request\\b"
]

[categories]
allowed = []
rejected = [
    "Account Support",
    "Allocations",
    "ERCAP",
    "account support",
    "Workstation Support",
    "Hardware"
]

[resources]
allowed = []
rejected = [
    "Cori",
    "Gerty",
    "Cori cscratch",
    "Cori GPU",
    "NoMachine",
    "Cori Large Memory",
    "Hopper",
    "Edison",
    "Genepool",
    "NEWT",
    "JGI Web Server",
    "Cori Ex Vivo"
]
